services:

  server:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/code/public

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public:/code/public