version: '3'

services:

  server:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

  app:
    build: .
    restart: unless-stopped
    volumes:
      - noted_media:/app/media