# Generated by Django 4.1 on 2023-04-27 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='/avatars/user_male_circle_icon.png', upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=1000)),
                ('task_date', models.DateField()),
                ('add_at', models.DateTimeField(blank=True)),
                ('task_priority', models.BooleanField(default=False)),
                ('task_deleted', models.BooleanField(default=False)),
                ('task_trash', models.BooleanField(default=False)),
                ('task_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=250)),
                ('note_text', models.TextField()),
                ('add_at', models.DateTimeField(blank=True)),
                ('note_trash', models.BooleanField(default=False)),
                ('note_file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('note_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
