# Generated by Django 4.1.5 on 2023-01-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_time',
            field=models.DateField(blank=True),
        ),
    ]
