# Generated by Django 4.1 on 2023-05-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_note_pin_task_task_time_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
