# Generated by Django 4.0.1 on 2023-03-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_note_priority_alter_note_tags_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='note',
            name='note_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
