name: Continuous Integration

on:
  push:
    branches:
      - master

concurrency:
  group: master
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.REGISTRY_USER }}/noted:app-1.0
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: Configure SSH
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_key
#          chmod 600 ~/.ssh/github_key
#          cat >>~/.ssh/config <<END
#          Host target
#            HostName $SSH_HOST
#            User $SSH_USER
#            IdentityFile ~/.ssh/github_key
#            LogLevel ERROR
#            StrictHostKeyChecking no
#          END
#      - name: Run deploy
#        run: |
#          ssh target "cd ~/spoosk && source venv/bin/activate && cd spoosk && git pull && pip install -r requirements.txt && python3 manage.py makemigrations && python3 manage.py migrate && supervisorctl restart spoosk_gunicorn"